name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: write

jobs:
  setup-wrapper:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Check if Gradle Wrapper exists
      id: check_wrapper
      run: |
        if [ ! -f "./gradlew" ]; then
          echo "wrapper_missing=true" >> $GITHUB_OUTPUT
        else
          echo "wrapper_missing=false" >> $GITHUB_OUTPUT
        fi
    
    - name: Generate Gradle Wrapper
      if: steps.check_wrapper.outputs.wrapper_missing == 'true'
      run: |
        gradle wrapper --gradle-version 8.5 --distribution-type bin
        chmod +x gradlew
    
    - name: Commit Gradle Wrapper
      if: steps.check_wrapper.outputs.wrapper_missing == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add gradlew gradlew.bat gradle/wrapper/
        git commit -m "Add Gradle Wrapper files for Java 17" || exit 0
        git push

  test:
    runs-on: ubuntu-latest
    needs: setup-wrapper
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        validate-wrappers: true
    
    - name: Verify Java version
      run: |
        java -version
        echo "JAVA_HOME: $JAVA_HOME"
        ./gradlew -version
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Build JAR
      run: ./gradlew jar
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: unzipper-jar-java17
        path: build/libs/*.jar
        retention-days: 30

  build-release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
    
    - name: Build release JAR
      run: ./gradlew clean build jar
    
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: unzipper-release-java17
        path: |
          build/libs/*.jar
          build/distributions/*
        retention-days: 90
