name: CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        java: [ '11', '17', '21' ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK ${{ matrix.java }}
      uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build with Gradle
      run: ./gradlew build
    
    - name: Run tests
      run: ./gradlew test
    
    - name: Build JAR
      run: ./gradlew jar
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: matrix.java == '11'
      with:
        name: unzipper-jar
        path: build/libs/*.jar
        retention-days: 30

  build-release:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582
    
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    
    - name: Build release JAR
      run: ./gradlew clean build jar
    
    - name: Upload release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: unzipper-release
        path: |
          build/libs/*.jar
          build/distributions/*
        retention-days: 90
