            - name: Update Gradle Wrapper Action
  # You may pin to the exact commit or the version.
  # uses: gradle-update/update-gradle-wrapper-action@512b1875f3b6270828abfe77b247d5895a2da1e5
  uses: gradle-update/update-gradle-wrapper-action@v2.1.0
  with:
    # Access token for the repository, e.g. `{{ secrets.GITHUB_TOKEN }}`.
    repo-token: # optional, default is ${{ github.token }}
    # List of users to request a review from (comma or newline-separated).
    reviewers: # optional, default is 
    # List of teams to request a review from (comma or newline-separated).
    team-reviewers: # optional, default is 
    # List of labels to set on the Pull Request (comma or newline-separated).
    labels: # optional, default is 
    # Base branch where the action will run and update the Gradle Wrapper.
    base-branch: # optional
    # Branch to create the Pull Request against.
    target-branch: # optional
    # Whether to set the `distributionSha256Sum` property in `gradle-wrapper.properties`.
    set-distribution-checksum: # optional, default is true
    # Use a custom base url to download the distributions file.
    distributions-base-url: # optional, default is 
    # List of paths where to search for Gradle Wrapper files (comma or newline-separated).
    paths: # optional, default is 
    # List of paths to be excluded when searching for Gradle Wrapper files (comma or newline-separated).
    paths-ignore: # optional, default is 
    # Gradle release channel to be used (either `stable` or `release-candidate`).
    release-channel: # optional, default is stable
    # Which merge method to use for auto-merge (either `MERGE`, `REBASE`, or `SQUASH`).  If unset, auto-merge will not be enabled on opened PRs.
    merge-method: # optional
    # Template used for PR title. Use %sourceVersion% and %targetVersion% to
refer to the source and target versions of the Gradle Wrapper.
There are cases in which the source version of the Gradle Wrapper can not
be determined successfully. In such cases, the string 'undefined' will be
used to replace the source version placeholder.

    pr-title-template: # optional, default is Update Gradle Wrapper from %sourceVersion% to %targetVersion%
    # Template used for PR description. Use %sourceVersion% and %targetVersion%
to refer to the source and target versions of the Gradle Wrapper.
There are cases in which the source version of the Gradle Wrapper can not
be determined successfully. In such cases, the string 'undefined' will be
used to replace the source version placeholder.

    pr-message-template: # optional, default is 
    # Template used for commit message. Use %sourceVersion% and %targetVersion%
to refer to the source and target versions of the Gradle Wrapper.
There are cases in which the source version of the Gradle Wrapper can not
be determined successfully. In such cases, the string 'undefined' will be
used to replace the source version placeholder.

    commit-message-template: # optional, default is Update Gradle Wrapper from %sourceVersion% to %targetVersion%
          
